### ISSUE TITLE
Iframe: Handling protocol relative URLs

### ISSUE THREAD

**Issue by tjwelde** [Lullabot/amp-library#125]
When I have a URL in the form `//example.org`, the library won't transform it to `https://`, which leads to a javascript error, because AMP only supports https in iframe src.

It could be handled in:
`Lullabot\AMP\Pass\IframeTagTransformPass -> getIframeSrc()`

But the `ActionTakenType` of `IFRAME_CONVERTED_AND_HTTPS` has to be changed in:
`Lullabot\AMP\Utility\ActionTakenType`

If that's ok, I can provide a pull request.

**Comment by sidkshatriya** [comment]
@goldquest Thanks for uncovering this edge case! 

The changes are merged to the master branch but do not exist in a tagged release yet. Closing.

**Comment by sidkshatriya** [comment]
Tagged release `1.0.3` now has this.

**Comment by tjwelde** [comment]
@sidkshatriya Thanks.
Could you also have a look at #33 ? If this would be resolved, we could use the library with our Drupal Distribution.
