### ISSUE TITLE
videos/carousels

### ISSUE THREAD

**Issue by alex-moreno** [Lullabot/amp-library#130]
Hi,

I am a bit confused on how we trigger the js for components like carousels or video.

We have a customised theme, with a field that we trigger in display suite. In the begining I tried using Preprocess variables for theme_hook, but this doesn't work as drupal_add_js gets removed in the template.php of amptheme.

What would be the right approach for this?

Thanks in advance.

**Comment by sidkshatriya** [comment]
You'll need to use AMP components. Custom Javascript components are not allowed in AMP. 

You'll need to include html for the carousel and the carousel javascript script tag (from google).

This might help:
https://ampbyexample.com/components/amp-carousel/

**Comment by alex-moreno** [comment]
Hi Sidharth,

yep, that's the issue, we already have included the html and the javascript
tag, but in templates and themes (kind of node-content-type.tpl.php). Then
the js is added in the html.tpl,php, but I don't think is the right place,
I was trying to make amp to put them in place, but given the architecture
we have atm with templates, that doesn't look to work... or we are not
doing it the right way maybe.

How would be the approach using amp components?

Thanks in advance
