### ISSUE TITLE
Youtube iframe without data-param-* causes warning

### ISSUE THREAD

**Issue by naeh** [Lullabot/amp-library#132]
Hello,

when trying de convert html containing youtube iframe without any data-param-\* it causes warning, here is an example of youtube tag :
`<iframe src="http://www.youtube.com/embed/zA_19bHxEYg" width="425" height="350"></iframe>`

here is the warning :
`Warning: Invalid argument supplied for foreach() in lullabot\amp\src\Pass\IframeYouTubeTagTransformPass.php on line 161`

the problem is that `BasePass::getQueryArray` returns bool or array but this is not controlled when used in IframeYouTubeTagTransformPass 

i think that `BasePass::getQueryArray` must always return an array (even empty)

**Comment by sidkshatriya** [comment]
@naeh Thanks for reporting this warning. Its been fixed and a new release tag 1.0.5 been created.
