### ISSUE TITLE
Core library should not depend on symfony/console

### ISSUE THREAD

**Issue by l0c0luke** [Lullabot/amp-library#134]

**Comment by sidkshatriya** [comment]
The version requirement is ^2.7.0 which means that any version >= 2.7.0 and <= 3.0.0 should work.

Sorry there are no plans to support symfony/console >= 3.0.0 at the moment.  Version 3.0.0 and higher change the compatibility requirement with the current code base (basically the amp-console command line utility). _Note_: The rest of the library does not care about symfony/console at all.

Drupal is also not on symfony 3.0.0 (and higher) last I checked. (Many people use this library from Drupal -- see https://www.drupal.org/project/amp).

It probably could be possible to remove the requirement for symfony/composer all together if you're simply using the library portion only. Then the console can use any symfony version and not affect anything else.

**Comment by edubuc** [comment]
I tried to use the library with Laravel 5.2 but I'm stuck too as it use symfony/console 3.0.9

Any tips on how I can use it anyway? (it will save me a lot of time)

Thanks

**Comment by yaquawa** [comment]
Yeah, same issue here with Laravel 5.3.
Would you consider separating the console part out from the library?

**Comment by sidkshatriya** [comment]
Ok I'll see how much work this change might entail.

**Comment by yaquawa** [comment]
Thanks sidkshatriya!!

**Comment by edubuc** [comment]
Thanks sidkshatriya

**Comment by sidkshatriya** [comment]
@yaquawa @edubuc @l0c0luke 

I think I've solved it. The solution was almost trivial (and obvious) in retrospect (see PR above). Before I merge to master / create a 1.0.x tag could any of you try it out?

In your project you can either do a: 
`composer require lullabot/amp:"dev-no-console-dep"`

or change the verson constraint for `lullabot/amp` in composer.json from (probably) `"^1.0.0"` to `"dev-non-console-dep"` followed by `composer update`

One this is confirmed to be OK I'll merge to master. (Subsequently you'll go back to version constraint `"^1.0.0"` -- so this is just for temporary testing purposes)

The change is on git branch `no-console-dep`. Composer refers to it as `dev-no-console-dep`

Also checkout https://packagist.org/packages/lullabot/amp#dev-no-console-dep

**Comment by FuzzyTree** [comment]
@sidkshatriya `composer require lullabot/amp:"dev-no-console-dep"` worked for me. Thanks!

**Comment by sidkshatriya** [comment]
Thanks @FuzzyTree for testing this out. Merged to master, created tag 1.0.7

`no-console-dep` branch deleted as this is on master / 1.0.7 tag.
