### ISSUE TITLE
Facebook video Embeds are not converted to AMP tag

### ISSUE THREAD

**Issue by pkailasusph** [Lullabot/amp-library#135]
Please update the regular expression to match all videos

`preg_match('&(*UTF8)facebook\.com/facebook/videos/\d+/?&i', $src)
`
should be changed to
`preg_match('&(*UTF8)facebook\.com/.*/videos/\d+/?&i', $src)`

**Comment by pkailasusph** [comment]
Updated. Please merge https://github.com/Lullabot/amp-library/pull/136

**Comment by sebastianbenz** [comment]
I've just pushed a new release 1.0.6 to [packagist](https://packagist.org/packages/lullabot/amp) which includes this change.
