### ISSUE TITLE
Do more comparisons with canonical validator 

### ISSUE THREAD

**Issue by sidkshatriya** [Lullabot/amp-library#14]
While porting a subset of the [canonical validator](https://github.com/ampproject/amphtml/tree/master/validator) to PHP comparisons were made between the output given by the canonical validator and our (ported) validator.

This exercise should happen again with greater rigour and with more sample HTML documents to ensure that the AMP HTML warnings that we report are correct.

Please note that the output will _not_ be the same between the two validators (and that is OK).  

Our validator will give:
- _More_ warnings in certain cases (e.g. the canonical validator will abort as soon as it sees a bad attribute, we report more problems. Our solution is better and helps us do more corrections later on)
- _Less warnings_ in certain cases as we don't support things like template, layout etc validation

We just need to ensure that our warnings are correct.

This ticket is partially related to #11 but not fully.

**Comment by sidkshatriya** [comment]
I think this is a good ticket to work on in the remaining time we have -- it will ensure that our validator is robust. It will help iron out any remaining bugs.

cc: @sirkitree

**Comment by sirkitree** [comment]
I'm not quite understanding how or why there would be two validators. If we already have one, that is sufficient for our purposes.

**Comment by sidkshatriya** [comment]
@sirkitree Basically all I want to do here is compare the results of our (ported PHP) validator with that the canonical validator ( https://github.com/ampproject/amphtml/blob/master/validator/validator.js ) on various sample HTML documents. ( The canonical validator is the "second" validator here).

This is just a correctness thing to make sure that our PHP validator is doing things correctly. In the future we will have CI/automated tests but now I'm just doing some additional manual testing and leaving it at that.

**Comment by sidkshatriya** [comment]
During testing, some small bugs (some were quite subtle) were discovered and were fixed. 

Refactoring was also done to simplify logic and lastly there were some cleanups to remove some "lints" in the code.

See PR #18 to see changes made (which also has correction logic improvements)

This is complete.
