### ISSUE TITLE
Small images are stretched to full width

### ISSUE THREAD

**Issue by FuzzyTree** [Lullabot/amp-library#143]
Small images (for example 50x50px) get stretched to full width because every `amp-image` gets the `layout='responsive'` attribute.

I propose giving images that are less than 300px (or some other constant) wide a layout attribute value of `fixed` instead of `responsive`, so the image doesn't get stretched to full width.

**Comment by sebastianbenz** [comment]
Makes sense. The width needs to be user configurable though.

**Comment by FuzzyTree** [comment]
Resolved by https://github.com/Lullabot/amp-library/pull/144
