### ISSUE TITLE
Make the HTML correction code more sophisticated

### ISSUE THREAD

**Issue by sidkshatriya** [Lullabot/amp-library#15]
One of the objectives of this library is to find _and_ automatically correct AMP HTML standard non-compliance automatically. 

So if a `style` attribute is illegal for a tag, we remove it. If a tag cannot exist in a particular location in the document we remove it and so on.

As mentioned in the `README.md` this correction is currently basic and can be made a bit more sophisticated.

**Comment by sidkshatriya** [comment]
For Phase 1 of the project I plan to spend very minimal time for this. We may end up leaving it as it is currently or at most add some small tweaks. 

Large increases in the sophistication of the "corrector" (e.g. additive correction in which we add missing tags rather than just removing bad tags and attributes, more intelligent correction of bad tag and attributes) is something that could be done in a Phase 2 of the project.

cc: @sirkitree

**Comment by sirkitree** [comment]
Agreed, thanks @sidkshatriya

**Comment by sidkshatriya** [comment]
The correction code was improved and made a bit more sophisticated:
- The correction code now deals with invalid or disallowed property value pairs in attributes; it removes these property pairs without disturbing other property value pairs in the same attribute
- The correction code was refactored in many places and is just generally cleaner and more robust
- If a mandatory property is missing from an attribute value, the attribute will _not_ be removed (correctness fix)
- Remove duplicate tags

This is merged and complete, closing.
