### ISSUE TITLE
Not converting <img> to <amp-img>, says image is not accessible, but it is

### ISSUE THREAD

**Issue by crittermike** [Lullabot/amp-library#173]
Here's my test code:

```php
$image_url = 'https://secure-cf-c.ooyala.com/c1a2V5dzrcamI62ib8aDq6ZDpNwXjXRO/promo268175626?1443909105518.jpg';
$amp = new AMP();
$amp->loadHtml("<img src='$image_url' />");
$amp_html = htmlspecialchars($amp->convertToAmpHtml());

// THIS WORKS FINE, RETURNS WIDTH AND HEIGHT
print_r(getimagesize($image_url));

// THIS IS STILL <img instead of <amp-img
print $amp_html;

print $amp->warningsHumanHtml();
```

It returns this output:

```
Array
(
    [0] => 1280
    [1] => 720
    [2] => 2
    [3] => width="1280" height="720"
    [bits] => 8
    [channels] => 3
    [mime] => image/jpeg
)
<img src="https://secure-cf-c.ooyala.com/c1a2V5dzrcamI62ib8aDq6ZDpNwXjXRO/promo268175626?1443909105518.jpg">
Transformations made from HTML tags to AMP custom tags
-------------------------------------------------------

<img src="https://secure-cf-c.ooyala.com/c1a2V5dzrcamI62ib8aDq6ZDpNwXjXRO/promo268175626?1443909105518.jpg"> at line 1
 ACTION TAKEN: img tag could NOT be converted to the amp-img tag as the image is not accessible.


AMP-HTML Validation Issues and Fixes
-------------------------------------
FAIL

<img src="https://secure-cf-c.ooyala.com/c1a2V5dzrcamI62ib8aDq6ZDpNwXjXRO/promo268175626?1443909105518.jpg"> on line 1
- The tag 'img' may only appear as a descendant of tag 'noscript'. Did you mean 'amp-img'?
   [code: MANDATORY_TAG_ANCESTOR_WITH_HINT  category: DISALLOWED_HTML_WITH_AMP_EQUIVALENT see: https://www.ampproject.org/docs/reference/amp-img.html]
```

So as you can see, the `getimagesize()` works fine on the image, meaning the image is accessible by PHP, so I'm not sure why AMP seems to think that it isn't.

I'm seeing this with multiple images from different domains, not just this single one, but not all - more than half work fine.

Any ideas?

**Comment by SGudbrandsson** [comment]
@mikecrittenden the AMP converter doesn't fetch the image itself.
It only converts the input and returns the amp valid output.
It doesn't fetch the actual image for processing since that will be very resource expensive (bandwidth and processing for every single AMP request).

See https://github.com/Lullabot/amp-library/blob/master/src/Pass/ImgTagTransformPass.php#L76

You need to set height and width to the image for the AMP converter to work properly.

Does that make sense?

**Comment by crittermike** [comment]
@sigginet I don't think that's true - it's supposed to dynamically fetch the width/height. The line directly above the one you linked says:

```
$this->setResponsiveImgHeightAndWidth($el);
```

And if you follow that call stack, you end up here: https://github.com/Lullabot/amp-library/blob/master/src/Pass/ImgTagTransformPass.php#L177

Note that `fastimage` is https://github.com/marc1706/fast-image-size which is a library specifically made for getting the image width/height by URL.

**Comment by SGudbrandsson** [comment]
Good point.. we can look into this, or you can try to debug this and create a new pull request (it would help a lot)..

**Comment by crittermike** [comment]
I figured it out - upgrading the fast-image-size package fixed it, thanks to this release: https://github.com/marc1706/fast-image-size/releases/tag/v1.1.2
