### ISSUE TITLE
PHP 5.5 reasoning

### ISSUE THREAD

**Issue by matt-harris-sift** [Lullabot/amp-library#174]
Hi

Would you be able to tell us what makes this library require PHP 5.5. As we are looking to install in on our servers which are running 5.3.

Thanks

**Comment by SGudbrandsson** [comment]
Hi @matt-harris-sift 

There are a number of changes between PHP 5.3 and 5.5.

You can try this library on a staging environment and see if it works for you or not.

But keep in mind that PHP 5.5 reached the EOL last June so the support may be dropped for it.

**Comment by ghost** [comment]
Yes, it's already difficult to support both PHP 5.5 and PHP 7. PHP 5.3 has even more differences, and is EOL.
