### ISSUE TITLE
Ambiguous class with composer

### ISSUE THREAD

**Issue by B-Prod** [Lullabot/amp-library#185]
When generating the autoload files, there are a lot of warning messages about ambiguous classes. For example:
Warning: Ambiguous class resolution, "Lullabot\AMP\Spec\AmpLayout" was found in both "/tmp/build/9062a266/code/vendor/lullabot/amp/src/Spec/validator-generated.php" and "/tmp/build/9062a266/code/vendor/lullabot/amp/src/validator-generated.php", the first will be used.
Warning: Ambiguous class resolution, "Lullabot\AMP\Spec\AmpLayoutLayout" was found in both "/tmp/build/9062a266/code/vendor/lullabot/amp/src/Spec/validator-generated.php" and "/tmp/build/9062a266/code/vendor/lullabot/amp/src/validator-generated.php", the first will be used.
Warning: Ambiguous class resolution, "Lullabot\AMP\Spec\AtRuleSpec" was found in both "/tmp/build/9062a266/code/vendor/lullabot/amp/src/Spec/validator-generated.php" and "/tmp/build/9062a266/code/vendor/lullabot/amp/src/validator-generated.php", the first will be used.
...

Should you not remove the classmap "src/Spec/validator-generated.php" from the autoload definition in the composer.json?
Or is this the expected behaviour?

**Comment by francoispottier** [comment]
Same issue here. Do we have to remove one or the other through composer.json?

Thanks!

**Comment by davereid** [comment]
I'm also getting the same error. It seems odd that src/validator-generated.php and Spec/valdiator-generated.php seem like the same file.

**Comment by davereid** [comment]
It looks like this file was added in https://github.com/Lullabot/amp-library/pull/182 but instead of updating the existing file, it was just duplicated. I'm working on a PR to remove the duplication.
