### ISSUE TITLE
Set up library on Packagist

### ISSUE THREAD

**Issue by ghost** [Lullabot/amp-library#19]
I started trying to set this up on Packagist and got the following error when I tried:

"Uncaught Exception: [RuntimeException] The HOME or COMPOSER_HOME environment variable must be set for composer to run correctly"

I think we need something added to composer.json to make packagist happy.

**Comment by sidkshatriya** [comment]
I'll investigate what the issue is here...

**Comment by sidkshatriya** [comment]
This is a local machine issue. On your local machine the environment variable HOME should be set to something. e.g. `env | grep HOME` should output something. See the comment https://github.com/composer/packagist/issues/393#issuecomment-132003244 for instance

Anyways see https://github.com/Lullabot/amp-library/issues/30 for further discussion on having the amp library on packagist.
