### ISSUE TITLE
data-captioned is not supported for instagram

### ISSUE THREAD

**Issue by pravinagham** [Lullabot/amp-library#193]
data-captioned is not validated & Parsed in output of instagram embedded string.

**Comment by pravinagham** [comment]
data-captioned is not present validator-generated . how to add attribute data-captioned in this file?

**Comment by pravinagham** [comment]
Any idea on how to add data-captioned

**Comment by jvrdom** [comment]
Hi @pravinagham in this PR we can fix this issue: #205

Cheers 🍻
