### ISSUE TITLE
Change README language regarding Composer

### ISSUE THREAD

**Issue by RainbowArray** [Lullabot/amp-library#2]
The section on Composer starts as follows:

```
If you're familiar with composer then you should not have any problems in getting this to work for your PHP project. If you're not familiar with composer then please read up on it before trying to set this up!
```

Perhaps change that to something like:

```
Use Composer to get this library working with your PHP project. Not familiar with Composer? Read on to learn more about how to get started.
```

Saying that setup steps are easy can trip people up when they run into unexpected problems. Not only can a setup step be frustrating, but now they are wondering why this wasn't easy. Better to just simply state what is needed to get started.

Other than that, great README!

**Comment by sidkshatriya** [comment]
Thanks for the suggestion -- I have made the language better now.
