### ISSUE TITLE
Run the Full HTML page through the library

### ISSUE THREAD

**Issue by sidkshatriya** [Lullabot/amp-library#20]
We discussed this on the call. We should run the Full HTML page through the library on amp paths on Drupal 8.

While the library will strip out any bad attributes, bad tags and bad property value pairs it does not know how to "add" things that would fix any potential problems. So you have two situations:
- An AMP page whose Full HTML was processed by the library, compliant in many more ways (but _possibly_ messed up in some ways because Drupal may depend on some of things we removed)
- An AMP page whose Full HTML was _not_ processed by the library so still has a few non-complying issues.

It may still be worthwhile to do this exercise and see if we're net positive by running the full HTML through the library. And hopefully we should.

cc: @sirkitree @mdrummond

**Comment by sidkshatriya** [comment]
Also @mdrummond has the main code on the module side that accomplishes this. This needs to be tested and fine tuned for any problems on both the module side and the library side.

**Comment by sidkshatriya** [comment]
To implement this we need changes both in the AMP library and AMP module. 

The above PR represents the changes in the library. It contains fixes and improvements to the library that happened while Full HTML mode was being tested. The chief new improvement is the ability to add `<script>` tags in `<head>` if the amp custom tags sneaked out from somewhere _without_ the amp module being able to add the corresponding `<script>` in head earlier.

**Comment by sidkshatriya** [comment]
@mdrummond @mtift Full HTML page processing ready to test on your localhost (Request your help in testing this please!)

Please make sure your library and module have the latest `master` and `8.x-1.x` branch commits respectively. Currently the Full HTML conversion is disabled by default and needs to be enabled in AMP config. 

As discussed, we will make Full HTML page processing _enabled_ by default -- but before that happens I'd like to request marc and mtift to test please.

You may track the progress on the Drupal module side here: https://www.drupal.org/node/2685509

For some additional context, here are some screenshots from the Drupal side of things (for those people uninterested in Drupal, ignore these screenshots).

![amp library config](https://cloud.githubusercontent.com/assets/638477/13699709/24657256-e7a2-11e5-8bc1-1eba2696a1ca.png)

If the 3rd checkbox is enabled you can go to: `admin/reports/dblog` (please filter by AMP module) and see a notice like the following:

![drupal log amp library](https://cloud.githubusercontent.com/assets/638477/13699727/4141eb34-e7a2-11e5-9d23-0ed1e21e83b1.png)

**Comment by mtift** [comment]
:+1: NIce work, @sidkshatriya!

**Comment by sidkshatriya** [comment]
Seems like things are working fine on this. Closing. Please re-open as necessary or assign a new bug if there are issues.
