### ISSUE TITLE
Font stylesheet from typekit is stripped out because it doesn't match the allowed font regex

### ISSUE THREAD

**Issue by bekapod** [Lullabot/amp-library#207]
AMP supports typekit (not sure as of when):

https://blog.typekit.com/2017/08/30/css-font-loading/
https://www.ampproject.org/docs/guides/responsive/custom_fonts

**Comment by andreaskoepke** [comment]
I have encountered this issue as well, rather frustrating.

**Comment by andreaskoepke** [comment]
I have tried to rebuild the  validator-generated.php file as per the instructions but for the new regex to be included the underlying validator code needs to be updated. I have attempted this but there are significant changes to the customised build.py and other files.

**Comment by bekapod** [comment]
Closing this as this doesn't affect me anymore and it persists in my github issues list (also, maybe it's already done, not sure 😃)
