### ISSUE TITLE
Use later version of sebastian/diff

### ISSUE THREAD

**Issue by pc-magas** [Lullabot/amp-library#209]
I try to install the `lullabot/amp-library` you provide over my php project but when I do it I get the following errors:

```composer
  Problem 1
    - Conclusion: don't install lullabot/amp 1.1.2
    - Conclusion: don't install lullabot/amp 1.1.1
    - Conclusion: remove sebastian/diff 2.0.1
    - Installation request for lullabot/amp ^1.1 -> satisfiable by lullabot/amp[1.1.0, 1.1.1, 1.1.2].
    - Conclusion: don't install sebastian/diff 2.0.1
    - lullabot/amp 1.1.0 requires sebastian/diff ~1.2 -> satisfiable by sebastian/diff[1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.4.2, 1.4.3].
    - Can only install one of: sebastian/diff[1.2.0, 2.0.1].
    - Can only install one of: sebastian/diff[1.3.0, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.0, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.1, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.2, 2.0.1].
    - Can only install one of: sebastian/diff[1.4.3, 2.0.1].
    - Installation request for sebastian/diff (locked at 2.0.1) -> satisfiable by sebastian/diff[2.0.1].
```
As you can notice I use a later version of `sebastian/diff` therefore I cannot install it. So can you provide a version that work with a later version of `sebastian/diff`?

**Comment by pc-magas** [comment]
I did the following pull request in order to fix it: https://github.com/Lullabot/amp-library/pull/211

**Comment by ghost** [comment]
This library is currently uninstallable on Drupal 8 projects created from Drupal Project, which I reported on Drupal AMP at https://www.drupal.org/project/amp/issues/2956657 and on Drupal Project at https://github.com/drupal-composer/drupal-project/issues/375. 

This fix might resolve that problem. I don't know if this will break other things or not and I'm not sure how to tell. However the linked patch does not break any tests.

**Comment by ghost** [comment]
I misspoke. The patch in #211 breaks tests but this patch works: [#219](https://github.com/Lullabot/amp-library/pull/219)

**Comment by ghost** [comment]
This has been pulled in and it solves the problems adding this package to Drupal 8.
