### ISSUE TITLE
Avoid instagram calls

### ISSUE THREAD

**Issue by guiajlopes** [Lullabot/amp-library#236]
Hi,

Is that possible to avoid Instagram calls in the convertion? I see that we make the call only to get the dimensions, I think using the default ones should be fine. Maybe we should have a parameter to allow or not allow calls.

I have some pages with a lot of instagram embedes and the page load takes a lof of time because of that

**Comment by m4olivei** [comment]
I also noticed this today. I had one transaction Trace in New Relic wherethe Instagram call hung for over 2min. I think at least, the connection should have a timeout.

**Comment by m4olivei** [comment]
@guiajlopes Would you mind taking a look at #273 ?
