### ISSUE TITLE
Declaration of Lullabot\AMP\Utility\AMPHTML5::parse error

### ISSUE THREAD

**Issue by bartekmis** [Lullabot/amp-library#247]
Hi,

today I have spotted very frustrating issue that broke my site...

`Declaration of Lullabot\AMP\Utility\AMPHTML5::parse(Masterminds\HTML5\Parser\InputStream $inputstream, array $options = Array) should be compatible with Masterminds\HTML5::parse($input, array $options = Array)`

Is there any chance you could fix that quickly?

**Comment by Cerzat43** [comment]
I had the same problem. To fix this error, I had to limit the version of `masterminds/html5` in my project.
```
"masterminds/html5": "2.3.*",
```

**Comment by bartekmis** [comment]
> I had the same problem. To fix this error, I had to limit the version of `masterminds/html5` in my project.
> 
> ```
> "masterminds/html5": "2.3.*",
> ```

Hi,

can you please let me know how you have managed to limit the version of `masterminds/html5`? In my Laravel project in composer.json I have only `"lullabot/amp": "^1.1"`. I do not want to edit the composer.json of the package in vendor of course. Is there any quick workaround for this issue until the official fix is on place?

**Comment by yasin749** [comment]
Hii
I did the version push

> `"masterminds/html5": "2.3.1"`

**Comment by Cerzat43** [comment]
@bartekmis you can add `"masterminds/html5": "2.3.*",` in your Laravel composer.json just after `"lullabot/amp": "^1.1"`.

**Comment by bartekmis** [comment]
> @bartekmis you can add `"masterminds/html5": "2.3.*",` in your Laravel composer.json just after `"lullabot/amp": "^1.1"`.

Hi,
thank you for your help, it worked like a charm (as a quick fix/temp workaround). It still would be super good if the official Lullabot/amp-library package was officialy fixed though.

**Comment by Cerzat43** [comment]
:+1:

**Comment by ghost** [comment]
The library has been pinned to 2.3 now.
