### ISSUE TITLE
Non Drupal PHP project

### ISSUE THREAD

**Issue by knolpad** [Lullabot/amp-library#26]
Hi,

I have a non-Drupal PHP website. It basically generates HTML files on the fly fetching from mysql database. In addition I have over 500 million HTML files that are generated on the fly as well. In case if you wondering what website is he talking about, head over to XYZCalledYou.com. 

I am looking for an automated AMP HTML file creation integration.

I was this close to finishing, but converting so many pages can be a nightmare that can't end at all.
In case if you are still wondering, the site never breaches, abuses or violates any of Google's terms of conduct.

I can send my PHP code over to you if you need to examine it.

Thank you,
Esh

**Comment by sirkitree** [comment]
Thank you, but we're not really interested in your custom implementation at this time. If you have questions regarding the operation of this library or suggestions for improvements, we'd be happy to collaborate.
