### ISSUE TITLE
is this repo dead?

### ISSUE THREAD

**Issue by chris-refactor73** [Lullabot/amp-library#266]
hi,
thank you for this great tool!
it works like charm for our purposes
but if i check the last modified dates it shows me it was modified years ago...
it would be nice if you could give me a hint: is this project still under maintenance, or is there another/better/up-to-date module for html2amp convertion?
thank you very much

**Comment by westonruter** [comment]
Based on recent conversations, the current plan is to extract the logic from the WordPress AMP plugin into an updated standard library for PHP-based CMSes to use for converting, sanitizing, and validating HTML as AMP. This would then be maintained under the AMP project. See https://github.com/ampproject/amp-wp/issues/2315.

**Comment by chris-refactor73** [comment]
Thank you!
