### ISSUE TITLE
Reconsider the project license

### ISSUE THREAD

**Issue by mtift** [Lullabot/amp-library#32]
Per https://www.drupal.org/node/2702125, we need to change LICENSE.txt to GPLv2

**Comment by mtift** [comment]
See also https://github.com/Lullabot/amp-library-issues/issues/4

**Comment by mtift** [comment]
Here is some more information from the chair of Drupal's [Licensing Working Group](https://www.drupal.org/governance/licensing-working-group):

> "Just to be clear, the library can be any license that is considered compatible with both GPLv2 and GPLv3 including MIT, GPLv2, or BSD.  It cannot be just GPLv3.  It would have to be GPLv2+."

**Comment by sidkshatriya** [comment]
There have been no updates on this issue for quite some time.

License remains unchanged i.e. Apache 2. Will re-open this ticket in case there are any further developments on this.
