### ISSUE TITLE
receives HTML and hands back AMP-HTML for analytics 

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/amp-library#8]

**Comment by sidkshatriya** [comment]
@sirkitree @karens 
Its a bit confusing what exactly I should do here (from a library perspective). What might need to be converted to the `<amp-analytics>` tag?

If I go to https://developers.google.com/analytics/devguides/collection/analyticsjs/ It gives me various ways I can add the google analytics script to the `<head>` of the document. Then there are javascript snippets like page tracking... (see: https://developers.google.com/analytics/devguides/collection/analyticsjs/pages )

``` javascript
ga('send', {
  hitType: 'pageview',
  page: location.pathname
});
```

Event tracking (see https://developers.google.com/analytics/devguides/collection/analyticsjs/events):

``` javascript
ga('send', {
  hitType: 'event',
  eventCategory: 'Videos',
  eventAction: 'play',
  eventLabel: 'Fall Campaign'
});
```

Now lets see what `<amp-analytics>` tag looks (from :
https://github.com/ampproject/amphtml/blob/master/extensions/amp-analytics/amp-analytics.md )

``` html
<amp-analytics>
<script type="application/json">
{
  "requests": {
    "pageview": "https://example.com/analytics?url=${canonicalUrl}&title=${title}&acct=${account}",
    "event": "https://example.com/analytics?eid=${eventId}&elab=${eventLabel}&acct=${account}"
  },
  "vars": {
    "account": "ABC123"
  },
  "triggers": {
    "trackPageview": {
      "on": "visible",
      "request": "pageview"
    },
    "trackAnchorClicks": {
      "on": "click",
      "selector": "a",
      "request": "event",
      "vars": {
        "eventId": "42",
        "eventLabel": "clicked on a link"
      }
    }
  }
}
</script>
</amp-analytics>
```

So it seems that the same information can be conveyed in the `<amp-analytics>` tag.
But client javascript to call google analytics is javascript with so many variations. Are we expected to write a parser to "understand" google analytics javascript, and then "convert" that into the `<amp-analytics>` tag?

Thats probably going to be a very complicated task given that there are so many variations in how this is done. Is it even a feasible / useful to the end user? 

Our Drupal 8 site is already generating an `<amp-analytics>` tag if the config is done in the AMP screens and it looks like this.

``` html
<amp-analytics type="googleanalytics">
  <script type="application/json">
    {
      "vars": {
        "account": "UA-9999999-99"
      },
      "triggers": {
        "trackAmpview": {
          "on": "visible",
          "request": "pageview"
        }
      }
    }
  </script>
</amp-analytics>
```

Would we like to propose some alternative tag conversions e.g dailymotion, vine etc. if this does not make sense? Or maybe I'm missing something obvious?

**Comment by mtift** [comment]
I don't understand why we would need the library to do this. Doesn't this happen in the theme using data from from the admin screen (`admin/config/content/amp`)?

cc @mdrummond

**Comment by sidkshatriya** [comment]
@mtift 
Yes, the AMP module+theme outputs a nice `<amp-analytics>` tag. But the tag is basic and the `<amp-analytics>` tag has many options.

[One could go crazy and the library could parse google analytics javascript code snippets (within `<script>`) (see my comment above) and "convert" them to `<amp-analytics>` tag with more options. But thats a mini project in itself and probably not very useful even.]

So it seems that library should not be doing anything here at all and we should close this ticket as `wontfix`.

**Comment by RainbowArray** [comment]
This happens in the module, not in the theme. But yes, this should not be anything the library needs to handle.

**Comment by mtift** [comment]
@sidkshatriya I agree. I think all of the configuration should be done in the module and output by the theme. I don't see any benefit of having a library that can parse analytics tags -- certainly not for a beta version, and probably not ever (or until someone can demonstrate a use case).

**Comment by sidkshatriya** [comment]
Great. Always love a `wonfix` ticket!

Is this something that was agreed in our agreement that the library would do specifically? If so do we need to tell them about it? Do we need to convey that it does not make sense and we can do something like vine or dailymotion etc. etc.?

**Comment by sirkitree** [comment]
We have a deliverable to "support ... amp-analytics". I suppose that is broad. Is what the module already doing supporting amp-analytics?

**Comment by sidkshatriya** [comment]
Yes the module+theme outputs a simple `<amp-analytics>` tag with the Google UA code like so:

``` html
<amp-analytics type="googleanalytics">
  <script type="application/json">
    {
      "vars": {
        "account": "UA-9999999-99"
      },
      "triggers": {
        "trackAmpview": {
          "on": "visible",
          "request": "pageview"
        }
      }
    }
  </script>
</amp-analytics>
```

**Comment by sirkitree** [comment]
I think we're okay for now then. This can remain closed. If you run out of things to do with the library, please start helping with the module.
