### ISSUE TITLE
receives HTML and hands back AMP-HTML for youtube 

### ISSUE THREAD

**Issue by sirkitree** [Lullabot/amp-library#9]

**Comment by sidkshatriya** [comment]
This is now working and merged to master.

The documentation has been updated to reflect this ( See https://github.com/Lullabot/amp-library/blob/master/README.md#what-is-the-amp-php-library )

![screenshot](https://cloud.githubusercontent.com/assets/638477/13491110/8ef238c2-e156-11e5-8ac0-ead76fbeadfe.png)

Closing ticket. Please re-open as necessary.
