### ISSUE TITLE
Support for <object><param name="movie" value="youtube.com" .../> to <amp-youtube> tag conversion

### ISSUE THREAD

**Issue by adonisfigueroa** [Lullabot/amp-library#95]
Support for conversion from "object movie" to "amp-youtube", ex:

```
<object width="512" height="308">
  <param name="movie" value="http://www.youtube.com/v/zAhJTxC1C8w?fs=1&amp;hl=en_US">
  <param name="allowFullScreen" value="true">
  <param name="allowscriptaccess" value="always">
    <embed src="http://www.youtube.com/v/zAhJTxC1C8w?fs=1&amp;hl=en_US" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="512" height="308">
</object>
```

Related plugin:
https://github.com/paulredmond/html-to-amp/blob/master/src/Converter/Extensions/YoutubeConverter.php

**Comment by sidkshatriya** [comment]
So you want youtube flash embed code conversion? It should not be too tough to implement but I've got some other items pending on my list. Let me think about it.

Thanks for the link -- thats a totally different project and our code bases are different. 

But as I mentioned -- it should not be too difficult as its just a matter of using regular expressions on the `<embed>` tag to get the youtube video id and creating a <amp-youtube> tag. We already have youtube `<iframe>` to `<amp-youtube>` embed code conversion for instance. Might that serve your purpose? (You can simply go in an replace all `<object>` embeds with `<iframe>` embeds in your system)

Will this workaround serve your purpose? How long can you wait?

**Comment by adonisfigueroa** [comment]
I made a fork from your project and now I have the conversion, Can I merge with your project? Maybe in other branch.
